# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PapaGeil' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Fix for React Native 0.83 C++ compatibility
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Use C++20 for React Native bridging and concepts support
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
        
        # Folly configurations - disable coroutines to avoid missing coro/Coroutine.h
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_NO_CONFIG=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_MOBILE=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_USE_LIBCPP=1'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'FOLLY_HAS_COROUTINES=0'
      end
    end
    
    # Patch Folly's Expected.h to force-disable coroutines
    `cd "#{Pod::Config.instance.installation_root}" && sed -i '' 's/#if FOLLY_HAS_COROUTINES/#if 0 \\/\\/ FOLLY_HAS_COROUTINES/g' Pods/RCT-Folly/folly/Expected.h 2>/dev/null || true`
    
    # Fix Hermes script phase warning by adding output files
    installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
      target_installation_result.native_target.build_phases.each do |build_phase|
        if build_phase.respond_to?(:name) && build_phase.name == '[CP-User] [Hermes] Replace Hermes for the right configuration, if needed'
          hermes_output = '${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/hermes.framework'
          build_phase.output_paths ||= []
          build_phase.output_paths << hermes_output unless build_phase.output_paths.include?(hermes_output)
        end
      end
    end
  end
end
